### ISSUE TITLE
ошибка: неверный ответ от капчи

### ISSUE THREAD

**Issue by yxzhin** [MegaSa1nt/GMDprivateServer#11]
![Снимок экрана 2023-11-12 124712](https://github.com/MegaSa1nt/GMDprivateServer/assets/134784079/bd727f9f-bce7-4a13-abb6-ef4e36a03c4d)
![Снимок экрана 2023-11-12 124730](https://github.com/MegaSa1nt/GMDprivateServer/assets/134784079/d4ce5d0f-63ea-4531-b387-5a1775b26deb)

**Comment by MegaSa1nt** [comment]
Скинь приватку

**Comment by yxzhin** [comment]
> Скинь приватку

https://yxzhin.000webhostapp.com/d/

**Comment by MegaSa1nt** [comment]
дешбоард обновлён до последней версии?

**Comment by yxzhin** [comment]
> дешбоард обновлён до последней версии?

да, я просто отредачил индекс.пхп чтобы кнопку кланы и сонги убрать

**Comment by MegaSa1nt** [comment]
хм, странно, ты точно правильные данные капчи в конфиге ввёл?

**Comment by MegaSa1nt** [comment]
хостинг не может каким-либо образом блокировать капчу?

**Comment by yxzhin** [comment]
> хостинг не может каким-либо образом блокировать капчу?

не, у меня был буквально пару месяцев назад гдпс на этом же ядре, и там все работало

**Comment by MegaSa1nt** [comment]
> не, у меня был буквально пару месяцев назад гдпс на этом же ядре, и там все работало

$captchaType у тебя какой выбран?

**Comment by yxzhin** [comment]
> $captchaType у тебя какой выбран?

1

**Comment by MegaSa1nt** [comment]
Ты можешь попробовать другие капчи? Допустим, Cloudflare Turnstile

**Comment by yxzhin** [comment]
> Ты можешь попробовать другие капчи? Допустим, Cloudflare Turnstile

могу попробовать

**Comment by yxzhin** [comment]
> Ты можешь попробовать другие капчи? Допустим, Cloudflare Turnstile
спасибочки, сработало. похоже, проблема на стороне самой по себе хкапчи

**Comment by MegaSa1nt** [comment]
Рад это слышать :)
