### ISSUE TITLE
сломанный incl

### ISSUE THREAD

**Issue by Evgenie3311** [MegaSa1nt/GMDprivateServer#12]
после загрузки папки incl на сервер дэшборд работает, но в игре профили и топы не загружаются

**Comment by MegaSa1nt** [comment]
Чзх, чо происходит, проверю, когда вернусь домой

**Comment by MegaSa1nt** [comment]
Попробуй ветку 2.2: https://github.com/MegaSa1nt/GMDprivateServer/tree/listscopy
