### ISSUE TITLE
Не выкладываются уровни

### ISSUE THREAD

**Issue by Evgenie3311** [MegaSa1nt/GMDprivateServer#125]
Во первых хочу обьяснить что эта проблема связана не только с этим ядром, но и с обычным от Cvolton'a. Дело в том что при выкладывании уровня появляется ошибка Upload Failed. Please try again later. Всё остальное в моём приватном сервере абсолютно полностью функционирует. Кто может помогите с этим, поскольку я перепробовал всё и ничего не дало результата

**Comment by Evgenie3311** [comment]
> Скачай HTTP Debugger, включи отображение ошибок на сервере, попробуй выложить уровень и отправь ошибку сюда

HTTP/1.1 500 Internal Server Error

**Comment by MegaSa1nt** [comment]
не включил отображение ошибок, добавь в `incl/lib/connection.php` это:
```php
ini_set('display_errors', 'On');
error_reporting(E_ALL);
```

**Comment by Evgenie3311** [comment]
> не включил отображение ошибок, добавь в `incl/lib/connection.php` это:
> 
> ```
> ini_set('display_errors', 'On');
> error_reporting(E_ALL);
> ```

добавил, но response остается прежним, или не там смотрю?

**Comment by MegaSa1nt** [comment]
если ты добавил всё правильно, то это parse error, обнови файл uploadGJLevel.php

**Comment by Evgenie3311** [comment]
> если ты добавил всё правильно, то это parse error, обнови файл uploadGJLevel.php

обновлён, я сегодня поставил начисто это ядро и заменил только /config/connection.php и добавил папку data

**Comment by MegaSa1nt** [comment]
покажи свой `incl/lib/connection.php`

**Comment by Evgenie3311** [comment]
> покажи свой `incl/lib/connection.php`

```
<?php
ini_set('display_errors', 'On');
error_reporting(E_ALL);
if(!isset($db)) global $db;
if(empty($db)) {
	error_reporting(0);
	include dirname(__FILE__)."/../../config/connection.php";
	include_once dirname(__FILE__)."/../../config/security.php";
	include_once dirname(__FILE__)."/../../config/dashboard.php";
	require_once dirname(__FILE__)."/ipCheck.php";
	$ic = new ipCheck();
	@header('Content-Type: text/html; charset=utf-8');
	if(!isset($port)) $port = 3306;
	try {
		$ic->checkIP();
		$db = new PDO("mysql:host=$servername;port=$port;dbname=$dbname", $username, $password, array(PDO::ATTR_PERSISTENT => true));
		$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
		$ip = $ic->getYourIP();
		if($activeBanIP) {
			$banip = $db->prepare("SELECT IP FROM bannedips WHERE IP=:ip");
			$banip->execute([':ip' => $ip]);
			$banip = $banip->fetch();
			if($banip != 0) exit(-1);
		}
		if(!isset($_SESSION['accountID'])) {
			$getExtID = $db->prepare('SELECT extID FROM users WHERE isRegistered = 1 AND IP = :ip LIMIT 1');
			$getExtID->execute([':ip' => $ip]);
			$getExtID = $getExtID->fetchColumn();
		}
		if($installed && (!empty($getExtID) || isset($_SESSION['accountID']))) {
			$accountIDcheck = $getExtID ?? $_SESSION['accountID'];
			$timezone = $db->prepare('SELECT timezone FROM accounts WHERE accountID = :id');
			$timezone->execute([':id' => $accountIDcheck]);
			$timezone = $timezone->fetchColumn();
			if(!empty($timezone)) date_default_timezone_set($timezone);
			else {
				$json = file_get_contents('http://ip-api.com/json/'.$ip);
				$ipData = json_decode($json, true);
				if($ipData['timezone']) {
					$update = $db->prepare('UPDATE accounts SET timezone = :tz WHERE accountID = :id');
					$update->execute([':tz' => $ipData['timezone'], ':id' => $accountIDcheck]);
					date_default_timezone_set($ipData['timezone']);
				}
			}
		}
	}
	catch(PDOException $e) {
		echo "Connection failed: " . $e->getMessage();
	}
}
?>
```

**Comment by MegaSa1nt** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/49565695/5da39ba3-8ba5-4962-851f-93453ce65e8d)

**Comment by Evgenie3311** [comment]
> ![image](https://private-user-images.githubusercontent.com/49565695/333255146-5da39ba3-8ba5-4962-851f-93453ce65e8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Nzk4MTIsIm5iZiI6MTcxNjQ3OTUxMiwicGF0aCI6Ii80OTU2NTY5NS8zMzMyNTUxNDYtNWRhMzliYTMtOGJhNS00OTYyLTg1MWYtOTM0NTNjZTY1ZThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE1NTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4OGJiZDM5M2MxZWE5OTQ4ODBjYTQ4MjZlYzBkYzRkNzBlNWExNTk2YzRlNDlmOThmNzhmMDkxZDRhY2Y1MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uYLqH9_bvF_HWhNu7vuWTVMhAuh-NgsyMNz5QO6cfaI)

ошибки начали высвечиваться, но теперь по какой то причине упал весь гдпс и в запросах мне выводит код 200 с контентом: `Connection failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'timezone' in 'field list'1,1`

**Comment by MegaSa1nt** [comment]
> ошибки начали высвечиваться, но теперь по какой то причине упал весь гдпс

гдпс не упал, ошибки мешают гд воспринимать ответ сервера
ты недоустановил приватку, поставь $installed = false в config/dashboard.php и открой дешбоард

**Comment by Evgenie3311** [comment]
> > ошибки начали высвечиваться, но теперь по какой то причине упал весь гдпс
> 
> гдпс не упал, ошибки мешают гд воспринимать ответ сервера ты недоустановил приватку, поставь $installed = false в config/dashboard.php и открой дешбоард

под словом упал я имел ввиду то что внутри клиента ничего не работает, сейчас попробую

**Comment by Evgenie3311** [comment]
> > ошибки начали высвечиваться, но теперь по какой то причине упал весь гдпс
> 
> гдпс не упал, ошибки мешают гд воспринимать ответ сервера ты недоустановил приватку, поставь $installed = false в config/dashboard.php и открой дешбоард

уровни так же не выкладываются, и в http debugger нет контента запроса как было буквально несколько сообщений назад, он полностью пустой, и код 500

**Comment by MegaSa1nt** [comment]
скинь приватку

**Comment by Evgenie3311** [comment]
> скинь приватку

https://qps.ps.fhgdps.com/gdps.zip

**Comment by Evgenie3311** [comment]
запускать ехе без восклицательного знака

**Comment by MegaSa1nt** [comment]
включи ошибки

**Comment by Evgenie3311** [comment]
> включи ошибки

![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/71527364/4c24c934-c14e-4ec6-abba-8a5623d9887b)
включены

**Comment by MegaSa1nt** [comment]
у меня ошибок нет

**Comment by Evgenie3311** [comment]
> у меня ошибок нет

дело было в отсутствующих переменных songIDs, sfxIDs и ts, их не было потому что сервер с 2.1 перенесён
