### ISSUE TITLE
SFX Library / Music Library problem

### ISSUE THREAD

**Issue by Evgenie3311** [MegaSa1nt/GMDprivateServer#126]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/71527364/86c5e6c4-4912-43e2-8530-936145d78da4)
Игра пытается найти файл которого нет в ядре, из-за чего список просто не прогружается, он пуст

**Comment by Evgenie3311** [comment]
Из файлов в этих папках только handler.php и .htaccess

**Comment by MegaSa1nt** [comment]
у тебя сервер на gdpsfh, он пока не полностью поддерживает моё ядро
