### ISSUE TITLE
Some Players cant upload Levels issue

### ISSUE THREAD

**Issue by JohnRickGDOfficial** [MegaSa1nt/GMDprivateServer#134]
Some players cannot upload their levels even the server is fine all online features is fine except the upload level.....i want to know why
![Screenshot_20240527-063416](https://github.com/MegaSa1nt/GMDprivateServer/assets/168163669/de65daf2-f38a-4f43-9585-9df30e232682)

**Comment by MegaSa1nt** [comment]
Some players can't, but some can?

**Comment by JohnRickGDOfficial** [comment]
Yes exactly

**Comment by MegaSa1nt** [comment]
Check if they somehow level upload banned

**Comment by JohnRickGDOfficial** [comment]
How do i check the level upload banned?

**Comment by MegaSa1nt** [comment]
In phpmyadmin in table `users` column `isUploadBanned` should be 0

**Comment by JohnRickGDOfficial** [comment]
There's no column named isUploadBanned in my users table

**Comment by JohnRickGDOfficial** [comment]
Please i want to fix this

**Comment by MegaSa1nt** [comment]
> That's a problem then. Set the "dashboard" parameter in config/dashboard.php to false and go on your dashboard so that it can add the new modifications.

Be sure you're on the latest version of this repo

**Comment by JohnRickGDOfficial** [comment]
Ok thank you
