### ISSUE TITLE
The sfx library and NCS library are broken (2.206 version)

### ISSUE THREAD

**Issue by FrostbiteGD** [MegaSa1nt/GMDprivateServer#138]
There is a bug present where the sfx library and NCS library are broken, there are no songs present and loading hangs leaving the libraries empty. Maybe the game clients will have to be updated after the update to 2.206.

**Comment by MegaSa1nt** [comment]
you're from GDPSFH, right? Wait for nginx rules to work

**Comment by FrostbiteGD** [comment]
No, my server supports Noxicloud, so it doesn't need nginx rules! With the new version the sfx library just stopped working, and I noticed that other people have also encountered this same problem.
