### ISSUE TITLE
Creator Points Got Reduced

### ISSUE THREAD

**Issue by JohnRickGDOfficial** [MegaSa1nt/GMDprivateServer#140]
Players got Complain about the Creator Points Drop or got reduced after the migration. Please fix this issue

**Comment by JohnRickGDOfficial** [comment]
Maybe the daily rewards creator point is not properly added to creators stats

**Comment by MegaSa1nt** [comment]
Before migration all epic creator points were doubled, and that was a bug, thay was fixed
