### ISSUE TITLE
Can't download new levels

### ISSUE THREAD

**Issue by VoomiTo421** [MegaSa1nt/GMDprivateServer#142]
Hi ! We finally fixed the problem of saving with my beautiful friend Yannordi thanks to your help :) 

But now when we try to play a new uploaded level it just don't want to play it, when we click the play button nothing happens. 
But the old uploaded levels work fine, even the 2.2 old levels we uploaded before the save fix work fine too.

Basically the 2.2 upload works but the server reading thinks that it's from 2.1.

**Comment by MegaSa1nt** [comment]
Is level data in `data/levels/ID`?

**Comment by yannordi** [comment]
@MegaSa1nt  hello the issue is that  (also with cvolton version) 2.2 level downloading doesnt work (upload works fine) but when downloading the level, the game says the game version is not 2.2 and i can only download 2.1 levels. tho the game is 2.2 and btw if in the database i change the level version from 22 to 21 it downloads fine in the game.

**Comment by MegaSa1nt** [comment]
What, can you show screenshot?

**Comment by yannordi** [comment]
@MegaSa1nt 
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/97634082/e5698688-9d52-4128-a567-34f9eb930f92)
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/97634082/e17a3270-8e97-4b2d-b742-26b7f9e46035)

22 game version levels cant be downloaded and theres a NA button

**Comment by MegaSa1nt** [comment]
What game version do you have

**Comment by yannordi** [comment]
2.2

**Comment by MegaSa1nt** [comment]
I mean 2.200/2.204/2.206, etc

**Comment by yannordi** [comment]
2.206

**Comment by MegaSa1nt** [comment]
What the hell, i have no clues why it doesn't let you open levels

**Comment by MegaSa1nt** [comment]
https://github.com/MegaSa1nt/GMDprivateServer/blob/master/incl%2Flevels%2FgetGJLevels.php#L280

Add `$level1["gameVersion"] = 21;` after this line

**Comment by yannordi** [comment]
i just saw that levels dont create in the data/levels folder

**Comment by VoomiTo421** [comment]
@MegaSa1nt Still no clue on why levels don't play ?

**Comment by VoomiTo421** [comment]
We fixed the problem ! Maybe my friend will tell how he did later today.
