### ISSUE TITLE
Can't open Gauntlets ("Something went wrong please try again later")

### ISSUE THREAD

**Issue by VoomiTo421** [MegaSa1nt/GMDprivateServer#144]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/55292372/67e1102c-67c1-476d-95ff-f28487002fa7)
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/55292372/7db6239a-c393-4ebb-a364-3b669b57a6cf)

After finally fixing the save and levels problems, we still got only one problem : Gauntlets don't open.

On GeometryDash.exe v2.206
We replaced the base64 link "http://www.boomlings.com/database" (1 replaced)
We replaced the normal links "www.boomlings.com/database" (57 replaced)

Don't understand why the gauntlets don't work, the server doesn't show any logs, don't recieve requests when clicked on a Gauntlet.

**Comment by MegaSa1nt** [comment]
try replacing https://www.boomlings.com/database instead of www.boomlings.com/database for normal links

**Comment by VoomiTo421** [comment]
> try replacing https://www.boomlings.com/database instead of [www.boomlings.com/database](http://www.boomlings.com/database) for normal links

Now it doesn't even load the gauntlets 

![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/55292372/4913b946-2bf3-48a5-b513-53d085749b19)

**Comment by MegaSa1nt** [comment]
Something wrong with links, will close, if you have more info, contact me on Discord: `sa1ntsosethui`
