### ISSUE TITLE
Getting a blank page when I go to any url in my GDPS

### ISSUE THREAD

**Issue by Kingminer7** [MegaSa1nt/GMDprivateServer#146]
I set up a GDPS on localhost and it just gives me blank pages. My config is unchanged since the database info is all correct.

**Comment by MegaSa1nt** [comment]
did you  open dashboard

**Comment by Kingminer7** [comment]
yes
any url, whether that be dashboard or something else, is blank

**Comment by MegaSa1nt** [comment]
turm on errors reporting and send what error says

**Comment by Kingminer7** [comment]
> turm on errors reporting and send what error says

i don't see any errors in the error log
i added `error_reporting(E_ALL & E_STRICT); ini_set('display_errors', '1'); ini_set('log_errors', '0'); ini_set('error_log', './');` and nothing showed

**Comment by Kingminer7** [comment]
> > > turm on errors reporting and send what error says
> > 
> > i don't see any errors in the error log i added `error_reporting(E_ALL & E_STRICT); ini_set('display_errors', '1'); ini_set('log_errors', '0'); ini_set('error_log', './');` and nothing showed
> > 
> > EDIT: This shows on dashboard now:
> > 
> > ```
> > 
> > Deprecated: Optional parameter $stars declared before required parameter $isCreatorBanned is implicitly treated as a required parameter in C:\Users\km7dev\Desktop\Other projects\GMDprivateServer\dashboard\incl\dashboardLib.php on line 948
> > 
> > Deprecated: Optional parameter $moons declared before required parameter $isCreatorBanned is implicitly treated as a required parameter in C:\Users\km7dev\Desktop\Other projects\GMDprivateServer\dashboard\incl\dashboardLib.php on line 948
> > 
> > Deprecated: Optional parameter $diamonds declared before required parameter $isCreatorBanned is implicitly treated as a required parameter in C:\Users\km7dev\Desktop\Other projects\GMDprivateServer\dashboard\incl\dashboardLib.php on line 948
> > 
> > Deprecated: Optional parameter $goldCoins declared before required parameter $isCreatorBanned is implicitly treated as a required parameter in C:\Users\km7dev\Desktop\Other projects\GMDprivateServer\dashboard\incl\dashboardLib.php on line 948
> > 
> > Deprecated: Optional parameter $userCoins declared before required parameter $isCreatorBanned is implicitly treated as a required parameter in C:\Users\km7dev\Desktop\Other projects\GMDprivateServer\dashboard\incl\dashboardLib.php on line 948
> > 
> > Deprecated: Optional parameter $demons declared before required parameter $isCreatorBanned is implicitly treated as a required parameter in C:\Users\km7dev\Desktop\Other projects\GMDprivateServer\dashboard\incl\dashboardLib.php on line 948
> > 
> > Deprecated: Optional parameter $creatorPoints declared before required parameter $isCreatorBanned is implicitly treated as a required parameter in C:\Users\km7dev\Desktop\Other projects\GMDprivateServer\dashboard\incl\dashboardLib.php on line 948
> > ```
> 
> Are you trying to run this on your PC without a PHP server installed?
> 
> Also, just add those lines in `incl/lib/connection.php` to enable error reporting everywhere:
> `ini_set('display_errors', 'On');`
> `error_reporting(E_ALL);`

I have a PHP and SQL server. I was going to localhost:80 where its hosted
