### ISSUE TITLE
Dashboard "redirects too many times"

### ISSUE THREAD

**Issue by Meowflow** [MegaSa1nt/GMDprivateServer#150]
Hello guys.
I don't know if this is a bug or something on my end, but the dashboard keeps redirecting too many times.
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/64538953/9a44395f-938e-405c-836a-6f0667178bc5)
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/64538953/94837abf-cd4f-4f81-b7e6-aa019be1f2fb)

Is there any way to solve this?

**Comment by MegaSa1nt** [comment]
Uhh glad to help
