### ISSUE TITLE
Login Failed happens on old accounts

### ISSUE THREAD

**Issue by Catstik** [MegaSa1nt/GMDprivateServer#16]
Activated accounts also don't count as activated if manually activated through database

**Comment by MegaSa1nt** [comment]
GD 2.2 uses different password checking (`gjp2`), try logging in in 2.1, using same save file for 2.2 and refreshing login, should work

**Comment by MegaSa1nt** [comment]
is this still a issue?

**Comment by Catstik** [comment]
I'll check

**Comment by Catstik** [comment]
idk, probably not though
