### ISSUE TITLE
NCS библиотека не работает

### ISSUE THREAD

**Issue by xan1230** [MegaSa1nt/GMDprivateServer#165]
Все библиотеки работают исправно, кроме ncs. В ней нет песен. 
![GeometryDash 2024-07-19 04-37-04-56](https://github.com/user-attachments/assets/2cd7d47d-e9e3-4e46-9263-262719a19047)

**Comment by MegaSa1nt** [comment]
Она есть, просто не помечена как ncs

**Comment by MegaSa1nt** [comment]
Немного попозже добавлю метку нцс

**Comment by Fenix668** [comment]
I don't know if you might be interested, but I think I understand why the server doesn't mark NCS songs. In the original server there is a link (in addition to that of YouTube and the WebSite which however is found in the other songs) there is a particular link which however was not inserted in your script, and is found in all the NCS songs of the original server. In fact, in the NCS songs "Download Soundtrack" does not come out (screen 1), while on the Robtop server "Download Soundtrack" comes out (screen 2) and is connected to a link (screen 3).

<img width="713" alt="screen" src="https://github.com/user-attachments/assets/c7dcfc37-e8b5-40c1-bb11-c34b20031494">
<img width="781" alt="screen 2" src="https://github.com/user-attachments/assets/da9d3101-4672-46d1-912c-5133f0c1662c">
<img width="406" alt="screen 3" src="https://github.com/user-attachments/assets/341c6971-65df-4ec3-bb11-9311b10790dd">

**Comment by Fenix668** [comment]
The NCS library also says that the songs are all connected to ncs.io
<img width="791" alt="screen 4" src="https://github.com/user-attachments/assets/26396298-d7bf-454f-baad-d94c87fe622a">

**Comment by Fenix668** [comment]
Try to see if it is possible to add this link to each song, and then another addition that should be made is to add the other artists who collaborated on those songs, in particular the NCS ones, to the authorID. Eh!de contributed to My Heart, but your script only recognizes that it was Different Heaven who made this song.

**Comment by MegaSa1nt** [comment]
> but I think I understand why the server doesn't mark NCS songs.

Because i didn't add ncs mark to server.
