### ISSUE TITLE
Make GD's Music and SFX Libraries IDs the same

### ISSUE THREAD

**Issue by M336G** [MegaSa1nt/GMDprivateServer#168]
Make it so that the Geometry Dash Music and SFX libraries song IDs are the same and not jumbled up every time you reset the custom library.

**Comment by MegaSa1nt** [comment]
Better to say: allow making library primary

**Comment by Fenix668** [comment]
Or even simpler, you can edit `/getCustomContentURL.php` and edit from:

```
<?php
include "incl/misc/getAccountURL.php";
?>
```

to:

`https://geometrydashfiles.b-cdn.net`

to have the default library. An advantage is that the NCS library is fully functional, but a problem is that custom SFX cannot be made available on the server. However, the music and sfx IDs will reflect the Geometry Dash server.
