### ISSUE TITLE
Add the --admin list-- to the "global" ranking of the leaderboard

### ISSUE THREAD

**Issue by Fenix668** [MegaSa1nt/GMDprivateServer#181]
When Cvolton made the commits to process GD's private server, on getGJScores.php he made a list available in "global" where only the server moderators, or in any case the most influential players, were available. It would be interesting to recreate this idea for those who want to have it on /config/misc.php, if you choose true you must also write the accountID of who you want to include in this list. Here's how Cvolton had done it:

**Comment by Fenix668** [comment]
<img width="548" alt="Screenshot 2024-08-03 212427" src="https://github.com/user-attachments/assets/7157fd06-6921-4d76-80fa-479581977016">

**Comment by MegaSa1nt** [comment]
Next commit

**Comment by Fenix668** [comment]
Cool! It has nothing to do with the problem, but could you add in `README.md` your google drive link where you keep the GD game versions? Especially now that version 2.207 is coming out, you could update it

**Comment by MegaSa1nt** [comment]
> Cool! It has nothing to do with the problem, but could you add in `README.md` your google drive link where you keep the GD game versions? Especially now that version 2.207 is coming out, you could update it

can't, because it is straight piracy, can only provide it in dms
