### ISSUE TITLE
File song upload via YouTube

### ISSUE THREAD

**Issue by M336G** [MegaSa1nt/GMDprivateServer#185]
Add a tab to upload songs with a YouTube URL via the [Cobalt API](https://github.com/imputnet/cobalt/blob/current/docs/api.md) (only if the song **file** reupload option is enabled, of course).

**Comment by masckmaster2007** [comment]
```php
<?php
$music = 'https://www.youtube.com/watch?v=bv0_KXEwNUw';
$data = array(
    "url" => $music,
    "aFormat" => "mp3",
    "isAudioOnly" => true
);

$postdata = json_encode($data);

$ch = curl_init("https://api.cobalt.tools/api/json"); 
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json', 'Accept: application/json'));
$result = json_decode(curl_exec($ch));
curl_close($ch);

$musicFile = $result->url;
```

Here's cobalt API already. Download link is stored at $musicFile.
It's possible.

**Comment by MegaSa1nt** [comment]
Are these links permanent?

**Comment by MegaSa1nt** [comment]
> Nah it uses the old API, so it'll probably be deprecated in the future

I mean output result links

**Comment by MegaSa1nt** [comment]
> Add a tab to upload songs with a YouTube URL via the [Cobalt API](https://github.com/imputnet/cobalt/blob/current/docs/api.md) (only if the song **file** reupload option is enabled, of course).

> hosted api instances (such as api.cobalt.tools) use bot protection and are not intended to be used in other projects **without explicit permission**

**Comment by MegaSa1nt** [comment]
ahh latah
