### ISSUE TITLE
Make a tools dedicated "reupload level" for songs and sfx from other servers

### ISSUE THREAD

**Issue by Fenix668** [MegaSa1nt/GMDprivateServer#189]
Always enhancement if you would like to add it: add a tool similar to "reupload level" but made for songs and sfx. In the advanced options enter the extension of the server from where the song/sfx is reuploaded, and in the empty space enter the ID of the song that was published on the linked server.

**Comment by MegaSa1nt** [comment]
you can use any gdps's song and sfx if you add it's library to config

**Comment by Fenix668** [comment]
Should I add [here](https://github.com/MegaSa1nt/GMDprivateServer/blob/master/config/dashboard.php#L44)?

**Comment by MegaSa1nt** [comment]
exactly
