### ISSUE TITLE
People having trouble with logging in.

### ISSUE THREAD

**Issue by Catstik** [MegaSa1nt/GMDprivateServer#19]
How do I generate everyone a gjp2 or is that something I just cant do

**Comment by MegaSa1nt** [comment]
they need to try to login in 2.1, also be sure, that you updated this file: https://github.com/MegaSa1nt/GMDprivateServer/blob/lists/incl/lib/generatePass.php

**Comment by Kingminer7** [comment]
Yeah I have the same problem. Fresh install, both for database and php. Using #22.
Dashboard says "An error has occured: Invalid ID!. Click here to try again."
Geometry Dash says "Login Failed."
No problem when using Cvolton:GMDPrivateServer/Lists.
