### ISSUE TITLE
Possible additions that could be implemented on messengers

### ISSUE THREAD

**Issue by Fenix668** [MegaSa1nt/GMDprivateServer#207]
### These are some improvements that could be implemented for the messenger option:

<img width="959" alt="Photo 2024-08-27 184504" src="https://github.com/user-attachments/assets/a594e4f1-4bc7-4043-b5f2-5d8ff6ce97b0">

<img width="256" alt="Photo 2024-08-27 191845" src="https://github.com/user-attachments/assets/95bd4232-b674-49f3-8876-84eafb29dc54">

1. Add the "reply" button to answer directly to messages and reply (copying and pasting the content) of the subject without having to rewrite it. ✅

2. Add the time when the last message was left next to the player's contact. ✅

3. Change the red circle present when new messages arrive and add above it the number of how many messages arrive to your profile, both near the players' contacts and near the "messenger" icon with the total number of all messages received. ✅

4. Add the option to ~~edit~~ and delete next to the sender's messages. ✅

5. Add read time ✅

**Comment by MegaSa1nt** [comment]
Nice! But not in next commit

**Comment by Fenix668** [comment]
> Nice! But not in next commit

Sure, so you make a dedicated commit for it ;)

**Comment by MegaSa1nt** [comment]
Another suggestion:
Be able to @ping players and #levels

**Comment by Fenix668** [comment]
> Be able to @ping players and #levels

Yeah! You could also add (to a specific role for moderators) the ability to click on like and enter the value of your choice for comments both on the account profile and for level comments.

**Comment by MegaSa1nt** [comment]
If player blocked you or has messages disabled, you can't write them

**Comment by MegaSa1nt** [comment]
Oh, you mean notify thing and chat at the left?

**Comment by Fenix668** [comment]
I mean the icon that appears here

<img width="299" alt="screenshot 2024-09-05 032808" src="https://github.com/user-attachments/assets/b5c268b9-498b-4f85-9337-8816c60e0304">

**Comment by MegaSa1nt** [comment]
You mean we need to hide this button when messaging is blocked, right?

**Comment by Fenix668** [comment]
Yes

**Comment by Fenix668** [comment]
Yes, I understood it was for messenger 😆

**Comment by MegaSa1nt** [comment]
Made: 
1.  Time ago
2. Ping @players and #levels 
3. Remove messenger icon if player has closed DMs

**Comment by Fenix668** [comment]
Another suggestion: add a small note under the sender's messages that says "viewed (time) ago" if the message is viewed by the recipient without a answer.

**Comment by Fenix668** [comment]
As for the SFX folder bug, I noticed that the issue came after the changes in this commit. Try to restore by putting the changes back as they were before and tell me if the folders return 22 instead of 4: https://github.com/MegaSa1nt/GMDprivateServer/commit/7dd36d7ccb75dc47db08baf78d9fade33518613b

**Comment by MegaSa1nt** [comment]
In next commit
