### ISSUE TITLE
Add an automatic cron job for creator points

### ISSUE THREAD

**Issue by Fenix668** [MegaSa1nt/GMDprivateServer#213]
Add an automatic cron job toggle for creator points in `misc.php`, which should count not only the cp of the rated levels, but also the shared points, the gauntlets points and the daily points. Make sure to remove the 30 seconds wait time (at least for the level rating) to optimize the speed of level rating, and avoid the error that you can't rate after 30 seconds.

**Comment by Lila2048** [comment]
I support this. Running cron manually gets annoying

**Comment by DarinoxGD** [comment]
-_-

Just include in file "suggestStars20.php" stroke -> "/tools/cron/fixcps.php"

EEEEEASY!

**Comment by MegaSa1nt** [comment]
In next commit
