### ISSUE TITLE
Add another locking toggle: rate certain levels in any way

### ISSUE THREAD

**Issue by Fenix668** [MegaSa1nt/GMDprivateServer#214]
Add, as for locking comments and updating levels, a column dedicated for locking the rating of some levels, with commands enabled in the roles. Furthermore, also add to `misc.php` the possibility to block the rating not of the single level, but of all the levels of the account of your choice (by entering the accountID), such as for a Reupload account and prevent the reuploaded levels from being rated. Or in the other case add a column directly on "accounts" instead of making a toggle on misc.php, it depends on how it is more convenient.

**Comment by MegaSa1nt** [comment]
I think this should be handled by GDPS owner, not by core
