### ISSUE TITLE
Add a role-managed personal safety check for global ranks before update leaderboards like on GD

### ISSUE THREAD

**Issue by Fenix668** [MegaSa1nt/GMDprivateServer#219]
An autoban, however, controlled and managed by authentic people instead of badly automated.
Usually on GD it takes a while before the global ranks are confirmed, and an idea would be to add a tool to check the new ranks of the star rankings and personally ban those who cheat or exceed the number expected by the stars before continuing the number of ranks of the game, so that a player who has rigged the number of stars does not randomly appear in the rankings, and above all is not seen by other players at the top of the leaderboard.

**Comment by Fenix668** [comment]
Another idea: add for those who have "isAdmin" enabled the possibility for moderators with a special role to ban the global rank of a cheater simply by blocking the user profile, so that in addition to automatically removing the rank, he disappears from the rankings. And do like on GD that when the rank is banned, the statistics automatically drop to zero (stars, diamonds, moons, user coins, demons etc...).

**Comment by MegaSa1nt** [comment]
Thought about it, same opinion as whitelists
