### ISSUE TITLE
Two quick bugs to fix on the dashboard

### ISSUE THREAD

**Issue by Fenix668** [MegaSa1nt/GMDprivateServer#227]
There is an error that occurs when you modify the values ​​of a created gauntlet, and it shows an error when you click on "change" (the writing turns red).

And then since you put item overflow on mobile devices (at least on mine which is an iPhone) the screens look like this:

![IMG_2259](https://github.com/user-attachments/assets/fe15359f-4e58-4658-9cfa-c52df69f0b5e)

You see a huge black space that almost hides the compilation screen for quests, map packs and gauntlets. On the PC it's different and it shouldn't come out like this.

**Comment by MegaSa1nt** [comment]
you didnt update cvolton.css
