### ISSUE TITLE
Bug account dashboard

### ISSUE THREAD

**Issue by TheIzquierdoGD** [MegaSa1nt/GMDprivateServer#233]

**Comment by MegaSa1nt** [comment]
Bug account dashboard no understand need describe

**Comment by TheIzquierdoGD** [comment]
![Captura de pantalla 2024-09-30 001430](https://github.com/user-attachments/assets/0808186f-155e-46ee-a89e-dba151f931a0)

**Comment by TheIzquierdoGD** [comment]
I try to log into my DASHBOARD account but it won't let me (X)

**Comment by MegaSa1nt** [comment]
You need to migrate gdps, then fix gdsp

**Comment by TheIzquierdoGD** [comment]
have a question Is the "Messenger" still in the testing phase?

**Comment by TheIzquierdoGD** [comment]
I ask because I get (X) should I migrate the gdps then?

**Comment by MegaSa1nt** [comment]
Yes, migrate, then fix

**Comment by TheIzquierdoGD** [comment]
thanks
