### ISSUE TITLE
ADD ROLES NOT WORK

### ISSUE THREAD

**Issue by TheIzquierdoGD** [MegaSa1nt/GMDprivateServer#235]
![image](https://github.com/user-attachments/assets/5becec10-ef80-49bf-a788-b804992c54fe)

**Comment by MegaSa1nt** [comment]
Try updating dashboard to latest version, then go to config/dashboard.php and set $installed to false, then open main dashboard's page

**Comment by TheIzquierdoGD** [comment]
Still not working

**Comment by TheIzquierdoGD** [comment]
In a previous version the "roles" did work, but when I migrated that option broke (It asks me for the Acc ID in PHP but Dashboard asks for the UserID and that creates confusion in the panel and the roles) or so I think.

**Comment by TheIzquierdoGD** [comment]
Ready, it worked for me
