### ISSUE TITLE
Level reupload doesn't work (returns HTTP 500)

### ISSUE THREAD

**Issue by Lila2048** [MegaSa1nt/GMDprivateServer#238]
https://github.com/user-attachments/assets/cb653f9e-8c76-4d5c-99e2-ad3f19176279

how to recreate the issue:

**Comment by MegaSa1nt** [comment]
Could you please send error logs?

**Comment by NebulaGMD** [comment]
How do i do that

**Comment by MegaSa1nt** [comment]
Can't tell you, depends on your hosting

**Comment by MegaSa1nt** [comment]
works for me /shrug
