### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RiaxStuff** [MegaSa1nt/GMDprivateServer#24]
is this capable of hosting a 2.2 GDPS? Is there a way to do so right now? Thanks

**Comment by MegaSa1nt** [comment]
Use https://github.com/MegaSa1nt/GMDprivateServer/pull/22

**Comment by RiaxStuff** [comment]
cant i just use this (yours) repo?

**Comment by RiaxStuff** [comment]
@MegaSa1nt

**Comment by MegaSa1nt** [comment]
yeah, of course!

**Comment by RiaxStuff** [comment]
@MegaSa1nt  account creation worked but i cant login, any suggestions?

**Comment by RiaxStuff** [comment]
@MegaSa1nt How do i fix chests? They wont load

**Comment by MegaSa1nt** [comment]
> @MegaSa1nt How do i fix chests? They wont load

daily? if so, check if you already opened chests before
