### ISSUE TITLE
where are the config/dashboard.php files

### ISSUE THREAD

**Issue by DropiWord** [MegaSa1nt/GMDprivateServer#240]
??? whereeeeee

**Comment by MegaSa1nt** [comment]
in ftp. this is GDPSFH question, unrelated to this repository

**Comment by DropiWord** [comment]
> ftp. this is GDPSFH question, unrelated to this repository

what?. ftp??

**Comment by DropiWord** [comment]
thx. in find it. srry for the problem an thank you for the repply
