### ISSUE TITLE
dashboard problem

### ISSUE THREAD

**Issue by maxann20** [MegaSa1nt/GMDprivateServer#242]
i just manually updated dashboard to the latest version and now i'm getting this error. help?

<img width="467" alt="Annotation 2024-10-13 033442" src="https://github.com/user-attachments/assets/6fbacd9f-6377-4cae-b5c3-b94557cc91f8">

**Comment by MegaSa1nt** [comment]
You overwrote config/connection.php, reset password in GDPSFH panel
