### ISSUE TITLE
BUG USERS? X3

### ISSUE THREAD

**Issue by TheIzquierdoGD** [MegaSa1nt/GMDprivateServer#244]
![image](https://github.com/user-attachments/assets/92111146-760d-4423-9047-9e42ea1811b3)

**Comment by MegaSa1nt** [comment]
never saw that

**Comment by MegaSa1nt** [comment]
![image](https://github.com/user-attachments/assets/24e45dee-9bad-4dd9-b60f-b57a02d9d59c)
you somehow dublicated accounts

**Comment by TheIzquierdoGD** [comment]
Can it be fixed?

**Comment by TheIzquierdoGD** [comment]
Oh, and thank you so much for fixing the bug that causes Addrol not to work.

**Comment by MegaSa1nt** [comment]
thats... why are your accounts table doesnt have unique flag on `accountID`

**Comment by TheIzquierdoGD** [comment]
![image](https://github.com/user-attachments/assets/a6dc3ebb-e34c-4d7e-86b4-b255a42b55c0)
I only get 1 non-triple account

**Comment by MegaSa1nt** [comment]
order by accountID (click on it)

**Comment by TheIzquierdoGD** [comment]
I have a copy of my DB and then added a new DB several times (I think that tripled the counts) AHHHH I ALREADY SAW IT WTF
![image](https://github.com/user-attachments/assets/53e09510-fbdf-4c5c-acf0-b42f0329bfd2)

**Comment by TheIzquierdoGD** [comment]
I'll try to correct it, sorry for the inconvenience

**Comment by TheIzquierdoGD** [comment]
Thanks for clarifying my doubts :3

**Comment by MegaSa1nt** [comment]
Yw
