### ISSUE TITLE
Little bug

### ISSUE THREAD

**Issue by TheIzquierdoGD** [MegaSa1nt/GMDprivateServer#265]
![image](https://github.com/user-attachments/assets/79b938e3-557d-4b4e-b866-7586e9e48cfb)
I don't know what's happening but every time I want to unban or do other actions some buttons don't work well or don't respond

**Comment by TheIzquierdoGD** [comment]
You tell me: There is something called PMA, It's also a bit annoying for secondary admins who don't have access to the PMA.

**Comment by MegaSa1nt** [comment]
Try reloading page

**Comment by TheIzquierdoGD** [comment]
Still not working

**Comment by TheIzquierdoGD** [comment]
I tried on other devices and it gives me the same result.

**Comment by MegaSa1nt** [comment]
will check later

**Comment by Lila2048** [comment]
Having the same issue. Also all of my songs start banned fsr

**Comment by MegaSa1nt** [comment]
> Also all of my songs start banned fsr

Check if you disable songs preenable in config/dashboard.php

**Comment by Lila2048** [comment]
> Check if you disable songs preenable in config/dashboard.php
what variable is that? I cant find it

**Comment by MegaSa1nt** [comment]
$preenableSongs, if you dont have it, that means you dont update your config file

**Comment by Lila2048** [comment]
yeah I save my config files when I update

**Comment by TheIzquierdoGD** [comment]
Sorry for the inconvenience, actually that problem I had was solved with the "migrate from FH" option. -Closed- :)

**Comment by Lila2048** [comment]
> Sorry for the inconvenience, actually that problem I had was solved with the "migrate from FH" option. -Closed- :)

So how do I fix this on my dashboard exactly?
