### ISSUE TITLE
Add on/off uninterrupted loading security for unregistered accounts.

### ISSUE THREAD

**Issue by Fenix668** [MegaSa1nt/GMDprivateServer#266]
There is a filter on GDPS that prevents (with uninterrupted loading) unregistered accounts from accessing the leaderboard, level comments, other players' profiles or gauntlets. Could you make an option on misc.php (or security.php is better) to choose whether to enable or disable this filter for those who want to enable it?

**Comment by MegaSa1nt** [comment]
its called $unregisteredSubmissions
