### ISSUE TITLE
Global Message to all your users (Idea)

### ISSUE THREAD

**Issue by TheIzquierdoGD** [MegaSa1nt/GMDprivateServer#272]
It is possible to do from PMA with this command

INSERT INTO messages (userID, userName, body, subject, accID, toAccountID, timestamp, secret, isNew)
SELECT 
    2, 
    'Izquierdo', 
    'YUZdV1BfUF0VVF0UQVxCRVFfVBFVURJYVF9HU19UQhRVWV5TVV4VR1hVEmZgfRgSUVhCV0dZQVRaEllQQhRfWl1UR0ZcUEIUCBwRHExmfHZ1YHd0fEkZ', 
    'VXJnZW50ZSEgTWVuc2FqZSBHbG9iYWw=', 
    71, 
    userID, 
    '1730355805', 
    0, 
    1
FROM users
GROUP BY userID;

But there is a bug (The message does not appear as new) but it does reach all GDPS accounts

-My suggestion would be that in the "Messages" (In Dashboard) section those who have certain permission can send this type of "Podcast" messages.

(The message is encrypted, I thought it was a base64 translation error. XD)

**Comment by Lila2048** [comment]
This would be useful for users who don't have Discord/your GDPS doesn't have a Discord. Seems like a good idea to me

**Comment by MegaSa1nt** [comment]
dont really like this idea

**Comment by EMREOYUN** [comment]
I think some servers need some kind of announcement thing. I'll give it a pass.
