### ISSUE TITLE
Automod bug?

### ISSUE THREAD

**Issue by TheIzquierdoGD** [MegaSa1nt/GMDprivateServer#284]
![image](https://github.com/user-attachments/assets/e1569a98-c688-433f-85b6-95c7cd00bc91)

I don't know if it's a bug or I don't know how to use "AutoMod" but it won't let me disable it, I get (X) or it doesn't tell me anything (I updated the gdps several times to the latest version and reinstalled) maybe it's in beta or I don't know.

**Comment by MegaSa1nt** [comment]
update gdps to latest version, go to config/dashboard.php, set $installed to false and try again

**Comment by MegaSa1nt** [comment]
Any progress?

**Comment by TheIzquierdoGD** [comment]
Dont work Xd
