### ISSUE TITLE
song upload doesnt work

### ISSUE THREAD

**Issue by Lncvrt** [MegaSa1nt/GMDprivateServer#287]
i cant at all get song uploading to work, i have to do it manually each time and its getting really old. is there a fix for this? https://xps.lncvrt.xyz/dashboard/songs its updated to the newest ver

**Comment by Lncvrt** [comment]
i looked at one of the older issues and you mentioned something about captcha but it still didnt work when disabled

**Comment by Lncvrt** [comment]
also seeing #228, im not using gdpsfh, im using my own server:
```
mariadb from 11.6.2-MariaDB, client 15.2 for debian-linux-gnu (x86_64) using  EditLine wrapper
Server version: Apache/2.4.62 (Ubuntu)
Server built:   2024-08-15T07:32:14
```

**Comment by MegaSa1nt** [comment]
Any error message? Or it just reloading page without uploading song? If so, max file size in your php configuration is too small

**Comment by Lncvrt** [comment]
> Any error message? Or it just reloading page without uploading song? If so, max file size in your php configuration is too small

it just refreshes, btw, can i have ur discord?

**Comment by MegaSa1nt** [comment]
`sa1ntsosethui`, increase max file upload size and max post size in your php.ini

**Comment by Lncvrt** [comment]
fixed, ty
