### ISSUE TITLE
Не загружаются уровни

### ISSUE THREAD

**Issue by MrNikitori** [MegaSa1nt/GMDprivateServer#32]
Уровни выкладываются, но не запускаются и не загружаются, пишет "Level download failed, please try again later". Права 777 стоят у папки Data.

**Comment by MrNikitori** [comment]
Если использовать level reupload, то вылезает ошибка 1005

**Comment by MegaSa1nt** [comment]
Попробуй выдать права 777 всему
Ошибка 1005 означает, что хостинг, который ты используешь, заблокирован на серверах РобТопа

**Comment by MrNikitori** [comment]
Выдал, всё равно та же ошибка

**Comment by MegaSa1nt** [comment]
Попробуй сначала импортнуть [этот файл](https://github.com/MegaSa1nt/GMDprivateServer/blob/listscopy/_updates/2023-11-23.sql), затем [этот файл](https://github.com/MegaSa1nt/GMDprivateServer/blob/listscopy/_updates/2023-12-20.sql)

**Comment by MrNikitori** [comment]
Импортнул, всё равно уровни не грузятся, даже новые

**Comment by MegaSa1nt** [comment]
Привет! Я дома, скинь свою приватку, попробую посмотреть, что с ней

**Comment by MrNikitori** [comment]
https://srvnikitori.7m.pl/

**Comment by MegaSa1nt** [comment]
у тебя https://srvnikitori.7m.pl/database/dashboard не была полностью установлена, попробуй сейчас

**Comment by MrNikitori** [comment]
> у тебя https://srvnikitori.7m.pl/database/dashboard не была полностью установлена, попробуй сейчас

неа, всё равно не загружаются
