### ISSUE TITLE
Не работает бэкап аккаунта (Account backup doesn't load/work)

### ISSUE THREAD

**Issue by licen150** [MegaSa1nt/GMDprivateServer#33]
Привет. При попытке переноса уровня на приватку вылезает ошибка
В логах пхп ничего нет, права на файлах 777, php8.2 fpm
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/38755713/a2ebe3ed-b7f9-4444-948b-909587272789)

**Comment by MegaSa1nt** [comment]
Привет, попробуй сначала импортнуть [этот файл](https://github.com/MegaSa1nt/GMDprivateServer/blob/listscopy/_updates/2023-11-23.sql), затем [этот файл](https://github.com/MegaSa1nt/GMDprivateServer/blob/listscopy/_updates/2023-12-20.sql)

**Comment by licen150** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/38755713/b9fee1c3-386e-443f-8bef-9120eb8e6cfc)
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/38755713/97cf10ae-9abb-4078-bd06-0da05722dc69)
1 и 2 файлы

**Comment by MegaSa1nt** [comment]
включи отображение ошибок: (выключи в incl/lib/connection.php)
```php
ini_set('display_errors', 'On');
error_reporting(E_ALL);
```
открой DevTools (F12), зайди во вкладку "Сеть", попробуй перезалить уровень, после найди levels/levelReupload.php в списке, нажми на "Предварительный просмотр" и отправь это сюда

**Comment by licen150** [comment]
при входе в дешборд висит это
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/38755713/6b6d0716-f081-4d31-84d1-08957ac85efa)

ошибка в levelReupload
https://pastes.dev/AH62TwHnP5

**Comment by licen150** [comment]
Еще не работает профиль в дешборде, бывает долго висит белый экран с надписьью "GDPS, 2024" и в целом он очень странно работает
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/38755713/0587a591-b041-45b5-b0c7-21f2c1d3d6a3)

**Comment by MegaSa1nt** [comment]
для levelReupload попробуй обновить [этот файл](https://github.com/MegaSa1nt/GMDprivateServer/blob/listscopy/dashboard/levels/levelReupload.php)
Насчёт профилей: ты используешь Apache или что-то другое?

**Comment by licen150** [comment]
реаплоад уровней теперь работает, спасибо 
У меня стоит nginx 1.18.0 и php-fpm 8.2

**Comment by MegaSa1nt** [comment]
> У меня стоит nginx 1.18.0 

У тебя есть возможность поставить https://github.com/e404/htaccess-for-nginx ? Профили работают на .htaccess

**Comment by licen150** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/38755713/29175ba5-5305-4cf1-a504-c6091d168b6e)

**Comment by MegaSa1nt** [comment]
Прости, не разбираюсь в этом

**Comment by licen150** [comment]
Он тут ругается на "/../" из за соображений безопасности
типо чтобы предотвратить file traverse в систему
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/38755713/20561bd0-0672-466f-9dd0-b7b5e9d8ec22)

**Comment by MegaSa1nt** [comment]
попробуй убрать `/../../profile`

**Comment by licen150** [comment]
я это уже понял

**Comment by licen150** [comment]
Еще при сохранении персонажа ошибка вылезает
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/38755713/bf04e04d-01be-43ce-95d4-b072621b9c37)

**Comment by licen150** [comment]
А, по этой проблеме уже писали даже

**Comment by MegaSa1nt** [comment]
Всё, я вернулся домой и могу нормально всё дебажить
Попробуй сначала это: https://github.com/MegaSa1nt/GMDprivateServer/blob/listscopy/accounts/backupGJAccount.php, если не поможет, скинь exe своей приватки или покажи, что сервер возвращает с включенными ошибками

**Comment by licen150** [comment]
Не помогло, и я не осилил включить вывод ошибок
https://files.licen777.ru/licengdps.exe

**Comment by MegaSa1nt** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/49565695/75c7afc3-a304-47e7-8942-f2f24e282521)

**Comment by licen150** [comment]
Дак у тебя же два раза database
И разве файл должен называться backupGJAccountNew.php а не просто backupGJAccount.php?

**Comment by MegaSa1nt** [comment]
> Дак у тебя же два раза database И разве файл должен называться backupGJAccountNew.php а не просто backupGJAccount.php?

я использую твой файл
да, он должен быть backupGJAccountNew.php

**Comment by licen150** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/38755713/8f4f5bd1-13a5-484a-85be-24270585bc06)
При попытке сохранения в запросах только это, никаких обращений к backupGJAccount не видно
Возможно я хреново сделал клиент поэтому щас переделаю и попробую еще раз

**Comment by licen150** [comment]
Еще раз переделал клиент и точно тоже самое

**Comment by licen150** [comment]
А, оно все правильно идет, тут именно с нгинксом мне сейчас надо ковыряться походу

**Comment by licen150** [comment]
Слушай, сейчас уже очень поздно и у меня голова вообще не варит
Давай я завтра тогда поковыряюсь с этим и уже напишу что в итоге у меня вышло

**Comment by MegaSa1nt** [comment]
Спокойной ночи!

**Comment by licen150** [comment]
Привет снова
Так и не смог я разобраться в этом, все равно все та же ошибка

**Comment by licen150** [comment]
И с профилями бы тоже стоило бы разобраться

**Comment by MegaSa1nt** [comment]
Привет, не шарю за nginx, он должен в `profile` или `messenger` или `clan/index.php` передавать значение после /
