### ISSUE TITLE
Gauntlets are broken

### ISSUE THREAD

**Issue by Aussiergd** [MegaSa1nt/GMDprivateServer#34]
It just shows the actual game levels and for the 2.2 gauntlets it says "something went wrong".
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/129812105/443490d9-811b-4403-8a30-6bd3e8b9c3c0)

**Comment by MegaSa1nt** [comment]
forgot to change base64 link

**Comment by Aussiergd** [comment]
how do I fix it?

**Comment by MegaSa1nt** [comment]
> how do I fix it?

Change base64 link
