### ISSUE TITLE
The Dashboard doesn't exist 

### ISSUE THREAD

**Issue by Ricky360** [MegaSa1nt/GMDprivateServer#36]
![Screenshot_20240110-214750](https://github.com/MegaSa1nt/GMDprivateServer/assets/78783028/e4fd3e5f-88fb-4345-b89d-98c50faa3e27)

**Comment by MegaSa1nt** [comment]
You didnt installed some SQL

**Comment by Ricky360** [comment]
![Screenshot_20240111-064201~2](https://github.com/MegaSa1nt/GMDprivateServer/assets/78783028/a72afe67-9456-46c6-b2dd-1ffa7b86fbae)

When i upload music it doesn't show up a result...i keep tapping the upload button but theres no changes

**Comment by MegaSa1nt** [comment]
Does something shows up at right bottom?

**Comment by Ricky360** [comment]
No, There's no indication and when i check to database that song doesn't show up

**Comment by MegaSa1nt** [comment]
Can you send me your GDPS?

**Comment by Ricky360** [comment]
http://insidiousgd.7m.pl/database/dashboard/

**Comment by MegaSa1nt** [comment]
But you have different link on screenshots

**Comment by Ricky360** [comment]
http://insidiousgd.7m.pl/database/dashboard/songs/

**Comment by MegaSa1nt** [comment]
Disable captcha, you turned it on, but didnt configured

**Comment by Ricky360** [comment]
Here

**Comment by Ricky360** [comment]
Every features same as the issue

**Comment by Ricky360** [comment]
Yay it worked!! But then :(

![Uploading Screenshot_20240111-125750~2.png…]()

**Comment by Ricky360** [comment]
![Uploading Screenshot_20240111-125750~2.png…]()

**Comment by Ricky360** [comment]
![Uploading Screenshot_20240111-125750~2.png…]()

**Comment by Ricky360** [comment]
![Uploading Screenshot_20240111-130057~2.png…]()

**Comment by Ricky360** [comment]
When i upload there's an X Appearing to the bottom right corner

**Comment by Ricky360** [comment]
And some pages goes error "error appeared"

**Comment by MegaSa1nt** [comment]
> Disable captcha, you turned it on, but didnt configured

Turn off captcha and run `window.localStorage.volume = 0.2` in console

**Comment by Ricky360** [comment]
Idid i turned off and run with that code

**Comment by Ricky360** [comment]
https://johnrickgdps1.noxicloud.es/dashboard/

**Comment by Ricky360** [comment]
Here is my official link some page not working i just follow your steps properly

**Comment by MegaSa1nt** [comment]
can you set `error_reporting(E_ALL);` in incl/lib/connection.php?

**Comment by Ricky360** [comment]
Done

**Comment by MegaSa1nt** [comment]
are you sure? nothing changed

**Comment by Ricky360** [comment]
![Screenshot_20240111-132803~2](https://github.com/MegaSa1nt/GMDprivateServer/assets/78783028/7882a7f8-699a-4c97-82bb-6b413397455f)

**Comment by MegaSa1nt** [comment]
add this before it:
```php
ini_set('display_errors', 'On');
```

**Comment by Ricky360** [comment]
Ohhh i did it thank you!!!

**Comment by MegaSa1nt** [comment]
set `error_reporting(0);` in incl/lib/connection.php

**Comment by Ricky360** [comment]
Alright Thank you!!
