### ISSUE TITLE
Level download failed

### ISSUE THREAD

**Issue by pKunnn** [MegaSa1nt/GMDprivateServer#37]
Hey, i tried updating my gdps to 2.2 and it gives me that "Level download failed".
All levels are shown in the recent tab. The safe from weekly/daily also works and the leadboard.

I cant download levels (not even upload), all my files in the database folder has the "777" permission (except config) and my SQL is up-to-date.

Where did i messed up?

**Comment by pKunnn** [comment]
Fixed! The file database/incl/lib/generateHash.php from the newest brand simply just doesnt work. 
You should replace the file with [this one](https://github.com/MegaSa1nt/GMDprivateServer/blob/6556e20aef30b1f3102238d01b66dff66770e4c0/incl/lib/generateHash.php)

**Comment by MegaSa1nt** [comment]
> Fixed! The file database/incl/lib/generateHash.php from the newest brand simply just doesnt work. 
> You should replace the file with [this one](https://github.com/MegaSa1nt/GMDprivateServer/blob/6556e20aef30b1f3102238d01b66dff66770e4c0/incl/lib/generateHash.php) 

Strange, was `generateHash.php` from `lists` branch?

**Comment by pKunnn** [comment]
> > Fixed! The file database/incl/lib/generateHash.php from the newest brand simply just doesnt work.
> > You should replace the file with [this one](https://github.com/MegaSa1nt/GMDprivateServer/blob/6556e20aef30b1f3102238d01b66dff66770e4c0/incl/lib/generateHash.php)
> 
> Strange, was `generateHash.php` from `lists` branch?

yep, `lists` and `listscopy`.

being this the code that doens't work: 
```
<?php
//credits to pavlukivan for decoding and to IAD for most of genSolo
class GenerateHash {
	public static function genMulti($lvlsmultistring) {
		include dirname(__FILE__)."/connection.php";
		$hash = "";
		foreach($lvlsmultistring as $result) {
			$id = strval($result['levelID']);
			$hash = $hash . $id[0].$id[strlen($id)-1].$result["stars"].$result["coins"];
		}
		return sha1($hash . "xI25fpAapCQg");
	}
	public static function genSolo($levelstring) {
		$len = strlen($levelstring);
		if($len < 41)return sha1("{$levelstring}xI25fpAapCQg");
		$hash = '????????????????????????????????????????xI25fpAapCQg';
		$m = intdiv($len, 40);
		$i = 40;
		while($i)$hash[--$i] = $levelstring[$i*$m];
		return sha1($hash);
	}
	public static function genSolo2($lvlsmultistring) {
		return sha1($lvlsmultistring . "xI25fpAapCQg");
	}
	public static function genSolo3($lvlsmultistring) {
		return sha1($lvlsmultistring . "oC36fpYaPtdg");
	}
	public static function genSolo4($lvlsmultistring){
		return sha1($lvlsmultistring . "pC26fpYaQCtg");
	}
	public static function genPack($lvlsmultistring) {
		$lvlsarray = explode(",", $lvlsmultistring);
		include dirname(__FILE__)."/connection.php";
		$hash = "";
		foreach($lvlsarray as $id){
			$query=$db->prepare("SELECT ID,stars,coins FROM mappacks WHERE ID = :id");
			$query->execute([':id' => $id]);
			$result2 = $query->fetchAll();
			$result = $result2[0];
			$idstring = strval($result["ID"]);
			$hash = $hash . $idstring[0].$idstring[strlen($idstring)-1].$result["stars"].$result["coins"];
		}
		return sha1($hash . "xI25fpAapCQg");
	}
	public static function genSeed2noXor($levelstring) {
		$hash = "aaaaa";
		$len = strlen($levelstring);
		$divided = intval($len/50);
		$p = 0;
		for($k = 0; $k < $len ; $k= $k+$divided){
			if($p > 49) break;
			$hash[$p] = $levelstring[$k]; 
			$p++;
		}
		$hash = sha1($hash."xI25fpAapCQg");
		return $hash;
	}
}
?>

```

Well, at least for me, that didn't work

**Comment by pKunnn** [comment]
i believe that code it's in every branch, the old code worked like a charm

**Comment by MegaSa1nt** [comment]
> being this the code that doens't work:
> Well, at least for me, that didn't work

Not latest version actually, lol
If you have PHP <8 version, then i know the issue
https://github.com/MegaSa1nt/GMDprivateServer/blob/master/incl/lib/generateHash.php
