### ISSUE TITLE
Pretty sure Demon info isnt named correctly.

### ISSUE THREAD

**Issue by Catstik** [MegaSa1nt/GMDprivateServer#38]
Demon info variable is accurate but doesn't return anything to the client other than the fact that you can open it.

**Comment by Catstik** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/91972350/72899f99-6701-4906-ac5f-ed6c3e67ab99)
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/91972350/624b2b54-d45c-4b6d-846e-8a1de1fac0ca)

**Comment by MegaSa1nt** [comment]
Strange, shouldnt act like this, did you updated all files?

**Comment by Catstik** [comment]
Well there aren't gauntlets anymore but I could check

**Comment by Catstik** [comment]
yeah idk then

**Comment by Catstik** [comment]
You removed dinfog and dinfow

**Comment by MegaSa1nt** [comment]
> You removed dinfog and dinfow. Is that the problem?

nope, shouldnt

**Comment by Catstik** [comment]
then idk. does it work for you

**Comment by MegaSa1nt** [comment]
> then idk. does it work for you with 2.204?
> 

Didn't tried in 2.204 but pretty sure it should

**Comment by Catstik** [comment]
sorry if this is annoying or anything but could you just check real quick?

**Comment by MegaSa1nt** [comment]
https://github.com/MegaSa1nt/GMDprivateServer/blob/lists/incl/scores/updateGJUserScore.php
Can you try updating this file?

**Comment by Catstik** [comment]
I updated everything for scores and lib

**Comment by Catstik** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/91972350/dd435aeb-ef0f-42df-bf6b-d91bff623f43)
still 0

**Comment by Catstik** [comment]
I found it. if there arent any gauntlet demons nothing gets added, so I added 999 to the value and it worked lmao
before:
20,1,6,0,1,1,0,0,0,0,13,
after:
20,1,6,0,1,1,0,0,0,0,13,999

![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/91972350/c461a16c-acee-4d26-90d3-a96a55866aa1)

**Comment by MegaSa1nt** [comment]
thats very strange, it has check for emptyness, lol

**Comment by Catstik** [comment]
> thats very strange, it has check for emptyness, lol

But then after that it made it empty instead of just 0

**Comment by MegaSa1nt** [comment]
is this still an issue?
