### ISSUE TITLE
Levels dont load

### ISSUE THREAD

**Issue by simtlers** [MegaSa1nt/GMDprivateServer#39]
levels in-game just directly not load. there isnt anything there... i checked getGJLevels.php manually and whenever i open it from a browser it returns this:
![imagen](https://github.com/MegaSa1nt/GMDprivateServer/assets/87283628/69ff527f-e99e-46bc-84c3-9d400943a392)

**Comment by MegaSa1nt** [comment]
can you send your gdps link?
try setting `error_reporting` to 0 in incl/lib/connection.php

**Comment by InfernoZXV** [comment]
same thing happening to me

**Comment by InfernoZXV** [comment]
I figured it out - you need to replace getGJLevels.php with the newest version
