### ISSUE TITLE
Can't install dashboard, error 500 in install.php. Self Hosted server.

### ISSUE THREAD

**Issue by Nintendero65pro** [MegaSa1nt/GMDprivateServer#40]
Hello. Im running a self hosted server running MariaDB alongside Nginx to host stuff.
I already cofigured everything but my dashboard doesnt work correctly, it says i need to configure it but i can't, because when i try to use install.php script, it throws me an error 500. 

Something interesting its that it semi-works, the dashboard works but when i enter to a section and using the "Dashboard button" i get a cors policy error in console.

![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/88602322/bacb5e42-3248-49a5-8f22-0f1f3a7f631c)

Thanks :)

**Comment by MegaSa1nt** [comment]
1. GMDprivateServer (and dashboard) relies on Apache's .htaccess, so idk how this will work
2. Do you have config/dashboard.php file? Did you replaced all files?
3. CORS error happens cuz you have custom error redirect to http.cat

**Comment by Nintendero65pro** [comment]
1. in which way relies in apache's .htaccess? i cant just make my own htaccess for my location?
2. yeah i have the dashboard.php, what do you mean i replaced all the files?
3. yeah so that should be irrelevant

**Comment by RobokingsCosmos** [comment]
> 1. in which way relies in apache's .htaccess? i cant just make my own htaccess for my location?
> 2. yeah i have the dashboard.php, what do you mean i replaced all the files?
> 3. yeah so that should be irrelevant

Try editing your connection.php to match your sql port and phpadmin database that you made and ensure that your sensitive info is protected

**Comment by MegaSa1nt** [comment]
Added nginx.conf
