### ISSUE TITLE
I cannot start online levels

### ISSUE THREAD

**Issue by prodbykasu** [MegaSa1nt/GMDprivateServer#41]
I can't start any levels, so I can create and upload online levels, but when I press play it doesn't work.

Do you have Discord? Could you add me there please? I'm usually not that active on github
Here my Discord username: prodbykasu

**Comment by MegaSa1nt** [comment]
Do you have any levels data in data/levels folder?
My Discord is МегаСвятой#9096

**Comment by MegaSa1nt** [comment]
Fixed
