### ISSUE TITLE
Не создается файл с бэкапом аккаунта в папке keys

### ISSUE THREAD

**Issue by svlemogames** [MegaSa1nt/GMDprivateServer#43]
При сохранении аккаунта игра выдает сообщение об успешном сохранении, но при загрузке ошибку. Также на сервере отсутствуют файлы с сохраненными аккаунтами.
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/88778218/ee2a6501-797a-4b3e-ad24-d3cd5a46e797)
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/88778218/b7ff08bd-5c02-4c1f-99fa-3fd2f605c41e)
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/88778218/ac414300-6be6-40f4-acc8-6d829589847a)

**Comment by MegaSa1nt** [comment]
в папке keys ничего и не должно быть, проверь папку data/accounts
если ничего нет, попробуй выдать всем файлам и папкам права 777, после сохранить аккаунт

**Comment by svlemogames** [comment]
Все поставил, сохранил, не работает

**Comment by MegaSa1nt** [comment]
у тебя есть права создавать файлы?

**Comment by svlemogames** [comment]
уже решил, просто послал запрос, а он выдал ошибку, закоментировал строку с ошибкой и все заработало
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/88778218/5d484b0b-085c-4c63-af80-64c6e43a72a0)

**Comment by MegaSa1nt** [comment]
у тебя не последняя версия, это уже пофикшено
https://github.com/MegaSa1nt/GMDprivateServer/tree/listscopy
