### ISSUE TITLE
Navbar home button redirects incorrectly within subdirectories

### ISSUE THREAD

**Issue by luihh** [MegaSa1nt/GMDprivateServer#44]
In the dashboard, when I'm on a route within a subdirectory (I'm not sure if I explained myself well, here's an example: gdps.com/database/account/changePassword.php) and I try to go back to /dashboard using the Home button on the navbar, the route changes to /database/account instead of /database (this is based on the example; in another route, it stays within the subdirectory).

**Comment by MegaSa1nt** [comment]
try updating to latest version: 
https://github.com/MegaSa1nt/GMDprivateServer/tree/listscopy

**Comment by luihh** [comment]
That's the one I have

**Comment by MegaSa1nt** [comment]
did you pressed back button on your mouse or browser? its a bit buggy rn

**Comment by luihh** [comment]
It only happens when I press the home button in the navbar; if I use the back button (without clicking the navbar button), it returns to /dashboard normally.

**Comment by MegaSa1nt** [comment]
send me your gdps

**Comment by luihh** [comment]
https://lpasgdps.000webhostapp.com/dashboard/

**Comment by MegaSa1nt** [comment]
works fine for me

**Comment by luihh** [comment]
but try navigating to another page after reaching the dashboard
this is what happens to me
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/64665264/32666a11-a08f-41e7-b85d-5ad06cbaaf0c)

**Comment by MegaSa1nt** [comment]
i did this

**Comment by MegaSa1nt** [comment]
https://github.com/MegaSa1nt/GMDprivateServer/assets/49565695/072e030f-822d-49c5-8460-502ac147ca94

**Comment by luihh** [comment]
it turns out the issue was with my browser (Firefox) I tried using another browser and it worked fine
thanks
