### ISSUE TITLE
Update reuploaded levels

### ISSUE THREAD

**Issue by luihh** [MegaSa1nt/GMDprivateServer#45]
how can I update levels that have been reuploaded from RobTop's server? I tried reuploading them again, but it says that the level has already been reuploaded, so I don't know what to do

**Comment by MegaSa1nt** [comment]
i think you cant

**Comment by nojnis** [comment]
it depends on the host... most hosts are blocked from reuploading from robtops server so thats likely why

**Comment by luihh** [comment]
I can reupload levels from RobTop's server.
What I need is updating levels that were reuploaded from RobTop's server to the GDPS

**Comment by nojnis** [comment]
then i dont think u can without deleting the existing level

**Comment by MegaSa1nt** [comment]
It is planned to make

**Comment by MegaSa1nt** [comment]
Done
