### ISSUE TITLE
GJP2 Login Falied

### ISSUE THREAD

**Issue by VIRalZah** [MegaSa1nt/GMDprivateServer#47]
Есть такая проблема: игра отказывается входить в аккаунт без GJP2, Dashboard сразу выставляет и Password и GJP2, но при регистрации через саму игру GJP2 всегда равно NULL(я даже по приколу установил GJP2 из другого акка и все заработало) я так думаю, надо сделать в registerGJAccount.php установку GJP2
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/129858326/b76f50c6-e421-4398-b695-b4ad95bf0612)

**Comment by VIRalZah** [comment]
Вернее не совсем, при входе в Dashboard GJP2 устанавливается

**Comment by VIRalZah** [comment]
Проблема в GeneratePass
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/129858326/262b162d-84e4-4316-8290-21bfeb0d0e17)
То есть игра дает пароль как GJP2 а сервер этот GJP2 не присваивает

**Comment by MegaSa1nt** [comment]
не обновил все файлы

**Comment by VIRalZah** [comment]
Обновил, я качал последнюю версию, а да ветка "lists"

**Comment by MegaSa1nt** [comment]
попробуй использовать ветку listscopy

**Comment by VIRalZah** [comment]
Да, все верно, там это реализовано, но я сам уже пофиксил это таким же способ, Спасибо!
