### ISSUE TITLE
Nothing works, can't login can't open daily chests etc despite running connection.php

### ISSUE THREAD

**Issue by RobokingsCosmos** [MegaSa1nt/GMDprivateServer#48]
Yes i'm using the latest GD update

**Comment by MegaSa1nt** [comment]
What is the issue?

**Comment by RobokingsCosmos** [comment]
> What is the issue?

I was able to find one ocurrance of the base64 and the boomlings just got updated to https

**Comment by MegaSa1nt** [comment]
Base64 is still http

**Comment by RobokingsCosmos** [comment]
> Base64 is still http

Yeah i kinda tried that but nothing changes that was the one ocurrance i found in the latest executable

**Comment by MegaSa1nt** [comment]
Yeah, GD 2.2 has only one base64 link, so you're fine

**Comment by RobokingsCosmos** [comment]
hold on i'ma try it again and see

**Comment by RobokingsCosmos** [comment]
ok nvm i swapped to a new server

**Comment by RobokingsCosmos** [comment]
ok nvm i swapped to a new server
