### ISSUE TITLE
проблема гаунтлетов (повторная отправка)

### ISSUE THREAD

**Issue by Evgenie3311** [MegaSa1nt/GMDprivateServer#49]
прошлая тема была закрыта и проблема не была решена добавлением 3 гаунтлетов, https://cdn.discordapp.com/attachments/1030804230002454612/1205104012232359946/unknown_2024.02.08-13.52.mp4?ex=65d72792&is=65c4b292&hm=1f0cd28622819948c051b8cef3bbf4e8fdfb4f98de96f2ba2ea88ba92809f9f3& вот то самое видео с проблемой

**Comment by MegaSa1nt** [comment]
Ты добавил **ещё** 3 гаунтлета, чтобы получилось 4 гаунтлета?
Попробуй нажать на правую стрелку

**Comment by Evgenie3311** [comment]
> Ты добавил **ещё** 3 гаунтлета, чтобы получилось 4 гаунтлета? Попробуй нажать на правую стрелку

прошу прощения, я подумал что нужно ровно 3 гаунтлета, а не 4

**Comment by MegaSa1nt** [comment]
Не извиняйся)
