### ISSUE TITLE
lists

### ISSUE THREAD

**Issue by Evgenie3311** [MegaSa1nt/GMDprivateServer#50]
https://cdn.discordapp.com/attachments/1142097501533524051/1207279733255962674/unknown_2024.02.14-13.57_1.mp4?ex=65df11de&is=65cc9cde&hm=7e32f66721dde6e67a16d1473b2dcb3becb00a308e5334e3af74dae1828cdbcd&

листы загружаются во вкладке my lists, можно оценивать, писать комментарии, но в глобальной вкладке lists ничего нет

**Comment by MegaSa1nt** [comment]
Не там смотришь, это вкладка Top Lists, сюда попадают рейтнутые на фичур листы

**Comment by Evgenie3311** [comment]
> Не там смотришь, это вкладка Top Lists, сюда попадают рейтнутые на фичур листы

а как чекать чьи либо листы?

**Comment by Evgenie3311** [comment]
все, я разобрался, спасибо за помощь, я думал туда все листы попадают и я нашел где смотреть листы, извиняюсь
