### ISSUE TITLE
Уровни есть на серверах, но в игре их не видно [RU]

### ISSUE THREAD

**Issue by ILedoff** [MegaSa1nt/GMDprivateServer#51]
Лвла есть в БД и в FileZill'е, но их не видно в игре. **Остальные функции работают**. **(Лвла есть в викли и дейли и в них даже можно поиграть)**

![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/0bb861e4-c595-440a-ae35-af29ad0591a3)
![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/e5cdfda3-ba30-4ff5-b7ec-c3f4a375b42b)
![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/b7c6a81b-4ace-42a7-a15e-3814f301b5d1)
![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/ff1262bc-3ccc-4642-afda-ec803b95d503)
![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/f383b436-731b-41a7-907b-4d77c660087c)

Прошу помочь.

**Comment by ILedoff** [comment]
Я применил 4 последних .sql в phpmyadmin и перезаписал почти все файлы в FileZilla (кроме connection.php, commands.php и некоторых тулсов т.к. у меня там есть вручную написанные коды)

**Comment by MegaSa1nt** [comment]
В файле incl/lib/connection.php измени error_reporting на E_ALL и скинь свою приватку

**Comment by ILedoff** [comment]
> скинь свою приватку

мне файл с 2.2 скинуть? у меня на сайте залита 2.1 только
https://irg.bccst.ru (он поломан немного т.к. домен сдох)

**Comment by ILedoff** [comment]
> измени error_reporting на E_ALL

не знаю правильно или нет, но заменил и всё тоже самое.
![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/d1cef4c4-30bf-4123-b16d-276291a2c2b8)

**Comment by MegaSa1nt** [comment]
> не знаю правильно или нет, но заменил и всё тоже самое. ![изображение](https://private-user-images.githubusercontent.com/150476436/311432092-d1cef4c4-30bf-4123-b16d-276291a2c2b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5ODM4NjUsIm5iZiI6MTcwOTk4MzU2NSwicGF0aCI6Ii8xNTA0NzY0MzYvMzExNDMyMDkyLWQxY2VmNGM0LTMwYmYtNDEyMy1iMTZkLTI3NjI5MWEyYzJiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQxMTI2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWI4ZWVmNGYzZTAwOTdhZTI4MzNmYzk5ZGFmOTc5MzcxNTUzMmY5Mzc4YTkxOGU4NGJkNGNlZTdkNjMyYjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HXE8TZRzqDjsZyhxcodZ4lOyo_qzTxXtjaRva-Dve18)

верни `error_reporting(0);`

**Comment by ILedoff** [comment]
> верни `error_reporting(0);`

Вернул

**Comment by ILedoff** [comment]
чё, я убрал "//" и заработало)
![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/8a7da67a-d271-4e3a-a1d4-2300e7e955a6)
у тебя в файле стоит "//" и поэтому не грузило, хотя на 2.1 тоже стояло и всё было норм

**Comment by ILedoff** [comment]
Закрою тему, всё решено в принципе, спасибо)

**Comment by MegaSa1nt** [comment]
у тебя старая версия сервера/не используешь мой репозиторий

**Comment by ILedoff** [comment]
> у тебя старая версия сервера/не используешь мой репозиторий

Твой поставил, всё ок!)
Кстати, ты знаком с Джулфором? Я посмотрел код и там есть его упоминание)

**Comment by MegaSa1nt** [comment]
Да, я ему помогал с переходом на 2.2

**Comment by ILedoff** [comment]
> Да, я ему помогал с переходом на 2.2

Понял). Он некоторое время помогал нам с сервером)
