### ISSUE TITLE
Проблема с звуковыми эффектами и некоторыми уровнями [RU]

### ISSUE THREAD

**Issue by ILedoff** [MegaSa1nt/GMDprivateServer#52]
Загрузил звук через эту ссылку: https://irg.bccst.ru/serv/database/dashboard/sfxs
В дешборде в файлзилле и бд они появились, а в игре бесконечная загрузка..
Пробывал заливать музыку через дешборд, её находит в игре.

![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/e2bafd89-814f-4e34-9bef-e23e92c5eac8)
![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/7b4dabaa-909b-4213-8ed8-2873ffd39a26)
![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/34eec3cb-f0cb-4ab8-bb08-fa849d6e8dab)
![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/9a2c16c2-30b4-47cb-9c61-a343aef4048c)

А еще некоторые уровни после обновления ушли в анлистед и если их оттуда вытащить, то они не будут грузится.

![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/14b12e5c-5479-4e2c-81e9-05810d6a5f5c)

**Comment by ILedoff** [comment]
![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/b7f91cdb-b2af-4372-aefc-25b50e126e15)

**Comment by MegaSa1nt** [comment]
на моей приватке щас последне-последняя версия библиотек, возможно, она пофиксит загрузку, но мне нужно кое-что ещё доделать, чтобы выложить её сюда
Насчёт последнего — проверь, есть ли в папке data файл уровня

**Comment by ILedoff** [comment]
> на моей приватке щас последне-последняя версия библиотек, возможно, она пофиксит загрузку, но мне нужно кое-что ещё доделать, чтобы выложить её сюда

Буду ждать, надеюсь пофиксится.

> Насчёт последнего — проверь, есть ли в папке data файл уровня

Проверил, файл в data есть.

![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/d3dd1f31-5631-4027-8cd5-7c6bc9ec0538)
![изображение](https://github.com/MegaSa1nt/GMDprivateServer/assets/150476436/e9ceb3fd-a605-4beb-abbb-9c8664a114b8)

Еще одну проблему нашёл. Уровни в Daily и Weekly не появляются, каждый раз когда таймер доходит до 00:00:00 таймер просто сбрасывается. (в dailyfeatures уровни появляются, в сейфе тоже). Может ли это быть из-за того, что я не обновлял commands.php? (у меня там просто свои команды добавлены)

Жду скорейшего ответа, ты уже во многом мне помогаешь :)

**Comment by MegaSa1nt** [comment]
пару дней назад я выложил обнову, у меня и других людей работает, проверь её

**Comment by MegaSa1nt** [comment]
Работает? Закрой проблему, если да
