### ISSUE TITLE
gd sfx dont work

### ISSUE THREAD

**Issue by Xytrizareal** [MegaSa1nt/GMDprivateServer#59]
the default gd sfx library doesnt work anymore

**Comment by Xytrizareal** [comment]
@MegaSa1nt

**Comment by MegaSa1nt** [comment]
Try last update

**Comment by Xytrizareal** [comment]
k

**Comment by Xytrizareal** [comment]
Uploading Desktop 2024.03.16 - 15.18.48.02.mp4…

i updated when it came out but it still doesnt work tf

**Comment by Xytrizareal** [comment]
https://github.com/MegaSa1nt/GMDprivateServer/assets/158840904/811087d0-09bc-466f-b983-2c079d94a4cb

**Comment by MegaSa1nt** [comment]
Delete .dat and .txt files from sfx and music libraries and try again

**Comment by Xytrizareal** [comment]
theres nothing even there its just htaccess and handerl.php

**Comment by MegaSa1nt** [comment]
You didn't replaced getCustomContentURL.php

**Comment by Xytrizareal** [comment]
ill see if i did or not

**Comment by Xytrizareal** [comment]
where is that file

**Comment by MegaSa1nt** [comment]
Root folder

**Comment by MegaSa1nt** [comment]
https://github.com/MegaSa1nt/GMDprivateServer/blob/master/getCustomContentURL.php

**Comment by Xytrizareal** [comment]
same content as that file says

**Comment by MegaSa1nt** [comment]
Try updating all files

**Comment by Xytrizareal** [comment]
ok

**Comment by Xytrizareal** [comment]
didnt work, i deleted every signle one and reuploaded from ur git repo and changed config/connection.php

**Comment by MegaSa1nt** [comment]
try hitting update button at the top right in-game

**Comment by Xytrizareal** [comment]
https://github.com/MegaSa1nt/GMDprivateServer/assets/158840904/35f0a5fa-ae2d-44d8-848d-886ed20397ee

still doesnt work

**Comment by MegaSa1nt** [comment]
you still somehow connected to main gd sfx library server instead of gdps one, are you sure you have right content in `getCustomContentURL.php`?

**Comment by Xytrizareal** [comment]
i want to use the main gd sfx's thought

https://github.com/MegaSa1nt/GMDprivateServer/assets/158840904/fa2000be-aa8c-4338-a824-7a39f3532d75

and yes i am sure

**Comment by Xytrizareal** [comment]
dw i changed password

**Comment by Xytrizareal** [comment]
i did it before upload, but thats basically what i did before and it STILL doesnt work

**Comment by MegaSa1nt** [comment]
deleted cuz password

this PR relies on htaccess, which is not supported by nginx (i think you have nginx?)
ill do nginx when i get server with it which supports changing nginx.conf

**Comment by Xytrizareal** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/158840904/b5693282-9987-4232-8511-efb21c3e5a3b)
it never sends a download log either its only fetch log

yes i have nginx

**Comment by Xytrizareal** [comment]
how do i make a server with apache thing

**Comment by Xytrizareal** [comment]
id prefer using nginx but is there a way to just get the main server sfx back?

**Comment by MegaSa1nt** [comment]
yeah, just change `getCustomContentURL.php`'s content to `https://geometrydashfiles.b-cdn.net` (just https://geometrydashfiles.b-cdn.net without anything else)

**Comment by Xytrizareal** [comment]
didnt work

**Comment by Xytrizareal** [comment]
nvm it works after game restart

**Comment by Xytrizareal** [comment]
ty

**Comment by Xytrizareal** [comment]
> this PR relies on htaccess, which is not supported by nginx (i think you have nginx?) ill do nginx when i get server with it which supports changing nginx.conf

@MegaSa1nt you can also just make a fresh 22.04 ubuntu server with cloud panel and manage it easily there, its really simple
