### ISSUE TITLE
players r formatted weird

### ISSUE THREAD

**Issue by Xytrizareal** [MegaSa1nt/GMDprivateServer#63]
they are {} Username for some reason in game

**Comment by Xytrizareal** [comment]
@MegaSa1nt !!!

**Comment by thejulfor** [comment]
These are clan tags, assign any tag to your clan on the dashboard

**Comment by Xytrizareal** [comment]
i dont want clans?

**Comment by thejulfor** [comment]
Then leave the clan you are in rn

**Comment by thejulfor** [comment]
The way it works is checking if the player is in the clan, if he is, then show clan tag in square brackets before the name.

@MegaSa1nt rewrote my php logic for this function so maybe he messed something up. For me it works perfectly on my server.

**Comment by Xytrizareal** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
idk how that shit works

**Comment by Xytrizareal** [comment]
i cant nginx is fucked up

**Comment by MegaSa1nt** [comment]
> The way it works is checking if the player is in the clan, if he is, then show clan tag in square brackets before the name.
> 
> @MegaSa1nt rewrote my php logic for this function so maybe he messed something up. For me it works perfectly on my server.

No, my code works fine
@Xytrizareal forgot to set his clan tag, therefore there is no tag

**Comment by MegaSa1nt** [comment]
> i cant nginx is fucked up

Not nginx issue

**Comment by Xytrizareal** [comment]
i don't want any fucking clans

**Comment by Xytrizareal** [comment]
dunno what they do and why they exist

**Comment by Xytrizareal** [comment]
there isn't any clans anyways it's just doing this to be annoying

**Comment by Xytrizareal** [comment]
> > The way it works is checking if the player is in the clan, if he is, then show clan tag in square brackets before the name.
> > @MegaSa1nt rewrote my php logic for this function so maybe he messed something up. For me it works perfectly on my server.
> 
> No, my code works fine @Xytrizareal forgot to set his clan tag, therefore there is no tag

![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/158840904/28f92801-c930-40d0-b911-26254bd1c0ce)

**Comment by Xytrizareal** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/158840904/d05459e4-1782-4818-8cbc-d33f8d76a1c0)

**Comment by Xytrizareal** [comment]
absolutely makes no sense

**Comment by Xytrizareal** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/158840904/bb78bd95-bea4-4bb3-a648-854191dd618a)

**Comment by Xytrizareal** [comment]
wow k...

**Comment by MegaSa1nt** [comment]
Ik

**Comment by Xytrizareal** [comment]
for now ill just fuck up the mainlib until it works

**Comment by Xytrizareal** [comment]
fixed 

```
	public function getUserString($userdata) {
		if($userdata['clan']) $userdata['userName'] = '['.$this->getClanInfo($userdata['clan'], 'tag').'] '.$userdata['userName'];
		$extID = is_numeric($userdata['extID']) ? $userdata['extID'] : 0;
		return "{$userdata['userID']}:{$userdata["userName"]}:{$extID}";
	}
```

into

```
	public function getUserString($userdata) {
		if($userdata['clan']) $userdata['userName'] = $userdata['userName'];
		$extID = is_numeric($userdata['extID']) ? $userdata['extID'] : 0;
		return "{$userdata['userID']}:{$userdata["userName"]}:{$extID}";
	}
```

**Comment by Xytrizareal** [comment]
just realized what i wrote is stupid but idc it works 🙃

**Comment by Xytrizareal** [comment]
@MegaSa1nt when will this be fixed

**Comment by Xytrizareal** [comment]
> The way it works is checking if the player is in the clan, if he is, then show clan tag in square brackets before the name.
> 
> @MegaSa1nt rewrote my php logic for this function so maybe he messed something up. For me it works perfectly on my server.

i think something got messed up

**Comment by MegaSa1nt** [comment]
https://github.com/MegaSa1nt/GMDprivateServer/commit/98fad6ffa0a2b6c385398e78aae3f3929ae59438

**Comment by Xytrizareal** [comment]
i think fixed
