### ISSUE TITLE
dashboard broken

### ISSUE THREAD

**Issue by crzylemon** [MegaSa1nt/GMDprivateServer#66]
Connection failed: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)
what happened?

**Comment by Xytrizareal** [comment]
you either didn't provide a password or you didn't make a mariadb/mysql
database to use

**Comment by crzylemon** [comment]
oh where does the password go?

**Comment by Xytrizareal** [comment]
config/connection.php in ur server url

**Comment by crzylemon** [comment]
ok

**Comment by Xytrizareal** [comment]
if fixed then close this issue as it isnt an actual problem its just you not knowing how this works

**Comment by MegaSa1nt** [comment]
Not related to dashboard
