### ISSUE TITLE
dashboard icons dont work

### ISSUE THREAD

**Issue by Xytrizareal** [MegaSa1nt/GMDprivateServer#67]
i tried refreshing my cache like so many times, deleted db files then reuploaded, still. 
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/158840904/0f5a77c8-fbaf-4dc2-9a9d-c219eecba785)

**Comment by Xytrizareal** [comment]
happened in the new sfx update, might revert back tbh

**Comment by Xytrizareal** [comment]
reverting to https://github.com/MegaSa1nt/GMDprivateServer/tree/b6b7870fa253e05d5f6fc4806cd347c8edd2cc39 worked

**Comment by MegaSa1nt** [comment]
https://github.com/MegaSa1nt/GMDprivateServer/tree/master/dashboard/incl/fontawesome
are you sure you have this folder?

**Comment by Xytrizareal** [comment]
i do

for whatever reason https://github.com/MegaSa1nt/GMDprivateServer/tree/b6b7870fa253e05d5f6fc4806cd347c8edd2cc39 is an absolute banger of a commit and doesnt have this (plus no clans :D)

**Comment by MegaSa1nt** [comment]
You should try latest update, it doesn't have "clans" in-game if you turned it off

**Comment by Xytrizareal** [comment]
the font is fucking broken tho

**Comment by MegaSa1nt** [comment]
Without fontawesome font ofc, will fix when get home

**Comment by Xytrizareal** [comment]
k ill try WHEN u get home and fix 👍

**Comment by Xytrizareal** [comment]
ID converter commit fixed this

**Comment by Xytrizareal** [comment]
still an issue so wont close
