### ISSUE TITLE
demonlist listings arent what i put

### ISSUE THREAD

**Issue by ghost** [MegaSa1nt/GMDprivateServer#73]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/158840904/4cb87992-6a11-465e-a240-4a81d8a31d89)

@MegaSa1nt

**Comment by Xytrizareal** [comment]
i didnt put tots at 1 or 10, complexity buff was at the LAST place, gtot by plux was legit the second last, i dont know why this happened

**Comment by MegaSa1nt** [comment]
I will rewrite demonlist, cuz code is bad

**Comment by Xytrizareal** [comment]
yeah,,,,

**Comment by Xytrizareal** [comment]
eta? :trollface:

**Comment by MegaSa1nt** [comment]
> eta? :trollface: 

Idk

**Comment by Xytrizareal** [comment]
hmMMMMMMMMMmmMMmm
