### ISSUE TITLE
Fix the account page by adding the diamond icon

### ISSUE THREAD

**Issue by Fenix668** [MegaSa1nt/GMDprivateServer#78]
In GDPS there is something to fix regarding the players page. The icon for the value of diamonds does not appear among the icons, and this is something that should be fixed.

Here's what it looks like on the official game page:

![2DE5F284-9EFB-4AAF-B632-FEB12DC70D04](https://github.com/MegaSa1nt/GMDprivateServer/assets/164776965/e8a1aebb-2990-4ae8-8db7-7dd5f0a3d468)

This instead appears in the GDPS:

![C6F9C68C-7FCF-4EB6-A3D2-CC0635CEEEB9](https://github.com/MegaSa1nt/GMDprivateServer/assets/164776965/fecc82e4-9d29-4dac-82b7-71a151097ee6)

**Comment by MegaSa1nt** [comment]
Update to latest version in https://github.com/MegaSa1nt/GMDprivateServer/pull/69

**Comment by Fenix668** [comment]
If the files to be updated are those present on "Forgot semicolons" and "Sure" I just did it, but still the diamond icon, with the value of those carried out, does not appear. Has the update already been released or are you doing it?

**Comment by MegaSa1nt** [comment]
https://github.com/MegaSa1nt/GMDprivateServer/blob/8f148c064c4f9e90661647fb39e02894ab59af42/incl/profiles/getGJUserInfo.php#L117C189-L117C214
Thats strange, because it is provided to the game

**Comment by Fenix668** [comment]
I checked, I had already added the /profiles file you sent following the clan updates, but the GDPS page still remains this one. The value of diamonds does not appear:

<img width="712" alt="Screenshot 2024-03-24 184625" src="https://github.com/MegaSa1nt/GMDprivateServer/assets/164776965/0a82cfd5-79c4-4f0d-899f-1bb3432d60ca">

even when, for example, I accumulate some:

<img width="719" alt="Screenshot 2024-03-24 184736" src="https://github.com/MegaSa1nt/GMDprivateServer/assets/164776965/1c343ab0-3f6f-4021-83ea-3792287a1e99">

**Comment by MegaSa1nt** [comment]
this is GD bug
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/49565695/595a09fe-b5d6-4ffc-a573-f22da8db31f9)
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/49565695/819a66b8-d219-4b97-8eba-9f655c9e32ba)

**Comment by Fenix668** [comment]
Yes, I later realized it was simply a bug. Thanks anyway
