### ISSUE TITLE
Не работает выкладывание музыки (не даёт ID)

### ISSUE THREAD

**Issue by Evgenie3311** [MegaSa1nt/GMDprivateServer#8]
https://qps.ps.fhgdps.com/dashboard/songs/

проблема началась после обновления на более новую версию дэшборда

**Comment by MegaSa1nt** [comment]
Я посмотрел, у тебя ОЧЕНЬ старая версия дэшборда

**Comment by Evgenie3311** [comment]
> Я посмотрел, у тебя ОЧЕНЬ старая версия дэшборда

Очень странно, я скачивал новую, и даже в этой версии дэшборда больше функций чем в прошлой

**Comment by MegaSa1nt** [comment]
> Очень странно, я скачивал новую, и даже в этой версии дэшборда больше функций чем в прошлой

замени все файлы

**Comment by Evgenie3311** [comment]
> > Очень странно, я скачивал новую, и даже в этой версии дэшборда больше функций чем в прошлой
> 
> замени все файлы

запустил по локалке сервер, тоже не помогло, грузит но не дает айди

**Comment by MegaSa1nt** [comment]
> > > Очень странно, я скачивал новую, и даже в этой версии дэшборда больше функций чем в прошлой
> > 
> > замени все файлы
> 
> запустил по локалке сервер, тоже не помогло, грузит но не дает айди

Очень странно

**Comment by MegaSa1nt** [comment]
А ты уверен, что FHGDPS позволяет заменять все необходимые файлы для дешборда? скачай последнюю версию и замени прям все файлы, которые можешь

**Comment by Evgenie3311** [comment]
> А ты уверен, что FHGDPS позволяет заменять все необходимые файлы для дешборда? скачай последнюю версию и замени прям все файлы, которые можешь

Я по локали запускал, то есть на своем ПК, не на хостинге, та же проблема

**Comment by MegaSa1nt** [comment]
Слушай, а ты включил загрузку файлов в php.ini? 
https://www.php.net/manual/ru/ini.core.php#ini.file-uploads
`file_uploads = 1`
`upload_max_filesize = 16MB`

**Comment by Evgenie3311** [comment]
> Слушай, а ты включил загрузку файлов в php.ini? https://www.php.net/manual/ru/ini.core.php#ini.file-uploads `file_uploads = 1` `upload_max_filesize = 16MB`

 завтра проверю

**Comment by MegaSa1nt** [comment]
>  завтра проверю

Не забудь про max_post_size
