### ISSUE TITLE
Не скачивается музыка из музыкальной библиотеки

### ISSUE THREAD

**Issue by xan1230** [MegaSa1nt/GMDprivateServer#81]
Сама музыкальная библиотека работает, но при скачивании оттуда музыки выдаёт ошибку.

**Comment by MegaSa1nt** [comment]
замени `https://www.newgrounds.com/audio/download/%i` на `твой домен/music/%i`

**Comment by xan1230** [comment]
Где

**Comment by MegaSa1nt** [comment]
в exe файле

**Comment by xan1230** [comment]
Все равно, та же самая ошибка
![Base Profile Screenshot 2024 03 29 - 12 56 31 68](https://github.com/MegaSa1nt/GMDprivateServer/assets/126078176/a14f86bd-0374-4279-b787-8df1cc1955dd)

**Comment by MegaSa1nt** [comment]
попробуй последнее обновление

**Comment by xan1230** [comment]
Не помогло

**Comment by MegaSa1nt** [comment]
скинь exe файл приватки

**Comment by xan1230** [comment]
https://drive.google.com/file/d/1et3CulXdcwQND5WKr51X7c70EesHh1Wn/view?usp=drivesdk

**Comment by MegaSa1nt** [comment]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/49565695/e198b625-4cf9-41f5-bace-871cf81b508f)
нет, ты не заменил ссылку

**Comment by MegaSa1nt** [comment]
[GeHi GDPS.zip](https://github.com/MegaSa1nt/GMDprivateServer/files/14884769/GeHi.GDPS.zip)
ты точно заменил все файлы при обновлении ядра приватки?

**Comment by xan1230** [comment]
> ![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/49565695/e198b625-4cf9-41f5-bace-871cf81b508f)
> нет, ты не заменил ссылку

Я пробовал и с измененной но все равно не работало

**Comment by xan1230** [comment]
> [GeHi GDPS.zip](https://github.com/MegaSa1nt/GMDprivateServer/files/14884769/GeHi.GDPS.zip)
> ты точно заменил все файлы при обновлении ядра приватки?

Да
