### ISSUE TITLE
sfxIDs keeps changing ID continuously!!

### ISSUE THREAD

**Issue by FrostbiteGD** [MegaSa1nt/GMDprivateServer#86]
Following the last update you made on the sfxs, it happened to me that every time I load new sfxs it turns out that every time I load the gdps library the IDs of those I loaded end up changing, and in doing so the levels where I insert sound effects will not find the sound effect I entered. Please if you have a way to check try to fix this bug!

**Comment by MegaSa1nt** [comment]
Dont delete sfx/ids.json

**Comment by FrostbiteGD** [comment]
I didn't delete it initially, but then after a while I had to do it because the IDs kept changing, and when I removed sfx/ids.json everything automatically returned to normal until recently, because then the IDs changed again.

**Comment by MegaSa1nt** [comment]
does this happen with latest commits?
