### ISSUE TITLE
некорректно отображаются комментарии к уровням

### ISSUE THREAD

**Issue by yxzhin** [MegaSa1nt/GMDprivateServer#87]
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/134784079/45881784-345e-4487-80a9-d0f30ca05f77)

вот как сам по себе стринг комментов выглядит
и это не из-за клантегов, проверял
upd: версия 2.204
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/134784079/65e724ea-a7e5-49de-9234-d693241be123)

**Comment by MegaSa1nt** [comment]
Забыл фикс залить, посмотри последний коммит

**Comment by yxzhin** [comment]
> Забыл фикс залить, посмотри последний коммит

да кстати, ты похоже еще забыл датабейз.скл апдейтнуть, в accounts не было колонны mail

**Comment by yxzhin** [comment]
> Забыл фикс залить, посмотри последний коммит
все, спасибки, работает
