### ISSUE TITLE
Проблема с отправлением на почту

### ISSUE THREAD

**Issue by svlemogames** [MegaSa1nt/GMDprivateServer#88]
![IMG_20240412_111920](https://github.com/MegaSa1nt/GMDprivateServer/assets/88778218/5bc6fd01-b8e1-45ec-b24b-0d678395aa52)

Изначально в базе данных в таблице accounts отсутствует mail из-за чего сообщения о подтверждении не отправляется на почту

**Comment by MegaSa1nt** [comment]
Добавил в последнем коммите. Почему-то он оттуда пропадает в третий раз
