### ISSUE TITLE
Suggest webhook

### ISSUE THREAD

**Issue by Fenix668** [MegaSa1nt/GMDprivateServer#94]
I find the idea of ​​adding webhooks for GDPS interesting, so if I were to add others I wanted to suggest if you could add a webhook for registering new accounts, and one instead for notifying new daily/weekly levels.

**Comment by MegaSa1nt** [comment]
Added daily/weekly webhooks

**Comment by Fenix668** [comment]
Okay perfect! As soon as I get back from job, I'll try to see if they work. By any chance, will the notification from the daily/weekly webhook arrive as soon as midnight strikes or at the end of the week? Or does it come when the command !daily or !weekly is entered?

**Comment by MegaSa1nt** [comment]
> Okay perfect! As soon as I get back from job, I'll try to see if they work. By any chance, will the notification from the daily/weekly webhook arrive as soon as midnight strikes or at the end of the week? Or does it come when the command !daily or !weekly is entered?

Both guesses are wrong :trollface:
It arrives when someone loads new daily level and only once

**Comment by MegaSa1nt** [comment]
I noted accounts suggestion as Admin Logs webhook, I'll close this to have less opened issues :trollface:
